---
title: "ATAC_preprocessing"
author: "Chenxin Li"
date: "11/4/2022"
output:  
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
library(tidyverse)
library(Seurat) 
library(Signac)
library(readxl)

library(RColorBrewer)
library(viridis)
library(rcartocolor)

library(patchwork)
```

# CRO3
## Data 
```{r}
CRO3_counts <- Read10X_h5(filename = "../Results/CRO_3/outs/filtered_feature_bc_matrix.h5")

CRO3 <- CreateSeuratObject(
  counts = CRO3_counts$`Gene Expression`,
  assay = "RNA"
)

CRO3[["ATAC"]] <- CreateChromatinAssay(
  counts = CRO3_counts$Peaks,
  sep = c(":", "-"),
  fragments = "../Results/CRO_3/outs/atac_fragments.tsv.gz"
)

CRO3
```
 

## Filter nuclei
```{r}
DefaultAssay(CRO3) <- "ATAC"
CRO3 <- NucleosomeSignal(object = CRO3)
```

```{r}
VlnPlot(
  object = CRO3,
  features = c('nCount_RNA', 'nCount_ATAC',
               'nucleosome_signal'),
  pt.size = 0,
  ncol = 3
) 


```
```{r}
CRO3$nCount_RNA %>% 
  as.data.frame() %>% 
  dplyr::rename(nRNA = ".") %>% 
  dplyr::filter(nRNA < 5000) %>% 
  ggplot(aes(x = nRNA)) + 
  geom_histogram(bins = 100, color = "white") +
  geom_vline(xintercept = 800, color = "tomato1") +
  theme_classic()

CRO3$nCount_ATAC %>% 
  as.data.frame() %>% 
  dplyr::rename(nATAC = ".") %>% 
  dplyr::filter(nATAC < 50000) %>% 
  ggplot(aes(x = nATAC)) + 
  geom_histogram(bins = 100, color = "white") +
  geom_vline(xintercept = 100, color = "tomato1") +
  theme_classic()
```


```{r}
CRO3 <- subset(
  x = CRO3,
  subset =  nCount_ATAC < 40000 &
    nCount_RNA < 5000 &
    nCount_ATAC > 100 & 
    nCount_RNA > 800 &
    nucleosome_signal < 2
)

CRO3
```

## GEX processing
```{r}
DefaultAssay(CRO3) <- "RNA"
CRO3 <- SCTransform(CRO3) 
CRO3 <- RunPCA(CRO3) 
CRO3 <- RunUMAP(CRO3, dims = 1:50, reduction.name = "umap.rna",
                reduction.kep = "rnaUMAP_")
```

## ATAC processing
```{r}
DefaultAssay(CRO3) <- "ATAC"
CRO3 <- FindTopFeatures(CRO3, min.cutoff = "q0")
CRO3 <- RunTFIDF(CRO3)
CRO3 <- RunSVD(CRO3)
CRO3 <- RunUMAP(CRO3, reduction = 'lsi', dims = 2:50, reduction.name = "umap.atac", reduction.key = "atacUMAP_")
```

## Joint UMAP
```{r}
CRO3 <- FindMultiModalNeighbors(
  object = CRO3,
  reduction.list = list("pca", "lsi"), 
  dims.list = list(1:50, 2:50),
  modality.weight.name = "RNA.weight",
  verbose = TRUE
)

# build a joint UMAP visualization
CRO3 <- RunUMAP(
  object = CRO3,
  nn.name = "weighted.nn",
  reduction.name = "wnn.umap",
  reduction.key = "wnnUMAP_"
)

```
```{r}
CRO3 <- FindClusters(CRO3, graph.name = "wsnn", algorithm = 3)
```


```{r}
CRO3_rna <- DimPlot(CRO3, label = TRUE, repel = TRUE, reduction = "umap.rna") +
  NoLegend() +
  theme_void() +
  ggtitle("RNA")

CRO3_atac <- DimPlot(CRO3, label = TRUE, repel = TRUE, reduction = "umap.atac") +
  NoLegend() +
  theme_void()+
  ggtitle("ATAC")

CRO3_joint <- DimPlot(CRO3, label = TRUE, repel = TRUE, reduction = "wnn.umap") +
  NoLegend() +
  theme_void() +
  ggtitle("Joint")

wrap_plots(
  CRO3_rna, CRO3_atac, CRO3_joint
) &
  NoLegend() &
  theme(plot.title = element_text(hjust = 0.5)) &
  theme(plot.margin = margin(t = 0, r = 3, b = 0, l = 0.5, unit = "lines")) 

ggsave("../Results/R_output/CRO3_UMAPs.svg", height = 3, width = 8, bg = "white")
ggsave("../Results/R_output/CRO3_UMAPs.png", height = 3, width = 8, bg = "white")
```
# Write out filtered object
```{r}
CRO3$run <- "CRO3"
DefaultAssay(CRO3) <- "RNA"

CRO3

saveRDS(CRO3, "../Results/R_output/CRO3_filtered.Rds")
```

CRO3: 1258 nuclei

```{r}
CRO3$nCount_RNA %>% summary()
CRO3$nFeature_RNA %>% summary()

CRO3$nCount_ATAC %>% summary()
CRO3$nFeature_ATAC %>% summary()
```

 

 




